sudo: false
language: node_js
node_js:
  - "8.9"
cache:
  directories:
    - node_modules

branches:
  only:
    - master # (PRs to master, master merges, master pushes)
    - next # consolidating branch for breaking changes

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: "UdU7dYh5Jef1yVYORQgpvRd3oVGi9UzPkoanUsAPF6Xmp/hpYN9bAG0nTnEE3OSFK4WehE2VdEQDtgvB/lgH6xgAmUcXv1ewNIZxRUvNQz7urYu6O+plbXlM+IUdDjOxGvj8P+ooWAiYuDYrChnfGOwcWydp1zOQc5RLmUSL9gi7E0hG119fCMPP+qJwaoDRpVQ2HdBQWLMCkcFqrRjYYEjf4ZYNhkNlL1jOx4+mgzbrezGL0jErnd9eX3ODt/NLH3NpX2XXt0WEYz9Q41HyMlV7eyUq/RHJRXWaksZYkEWHSitIJsjSOONFkBmEsLPD8VPS2fVYKfV1lXVoEVbERyy8HbbGDEbdm06DafOe3dB3+KSidSb95SyL8eUpdRetbySYyDSWsR4u8EF4Tr/SHUTl9ctOh6f0REvJzXjPRMM/uG+Pq5Fr+vGyA8YQj7n2LSvaw5zO2I07Nlf4MCFGY+CS0IE22AthnEptBKXbjFTFpLyTorkP5j8Tuvhru9BHZ3odJSOT2jFiZ5kxArbn5W+pg6Qiidm+JFmXZbtEVSsiS3HSJWXBxVJpBhWjMRpimKqdUMc272jyQ8KdEdpEVC0kEZtpE3Ul0ahdcIj492wnvhziGYHBR6s87fD4m9oPQ9r70iYQ3NcKbIo36uN7+Zd2w+C/jZr8XDIisg9NtI8="

before_install:
  - openssl aes-256-cbc -K $encrypted_ee3d73113e03_key -iv $encrypted_ee3d73113e03_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-api-proxy-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-api-state/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-app-render/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-app-route-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-app-server/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-auth-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-core/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-config/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-consumer/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-i18n/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-language-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-logger-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-router/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-store/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-sw-plugin/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-test-utils/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-toaster/.npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > packages/mwp-tracking-plugin/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

before_script:
  - lerna run build
  - lerna bootstrap
  - git diff --exit-code

script:
  - yarn flow
  - yarn test

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(npm bin)/set-up-ssh --key "$encrypted_ee3d73113e03_key" --iv "$encrypted_ee3d73113e03_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    lerna publish --yes --force-publish --skip-git --npm-tag $NPM_TAG --repo-version $GIT_TAG &&
    git tag -a $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git

after_success:
  - npm run coveralls
