sudo: false
language: node_js
node_js:
  - "7.8"
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master # (PRs to master, master merges, master pushes)
    - next # consolidating branch for breaking changes - need to build PRs

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: "UdU7dYh5Jef1yVYORQgpvRd3oVGi9UzPkoanUsAPF6Xmp/hpYN9bAG0nTnEE3OSFK4WehE2VdEQDtgvB/lgH6xgAmUcXv1ewNIZxRUvNQz7urYu6O+plbXlM+IUdDjOxGvj8P+ooWAiYuDYrChnfGOwcWydp1zOQc5RLmUSL9gi7E0hG119fCMPP+qJwaoDRpVQ2HdBQWLMCkcFqrRjYYEjf4ZYNhkNlL1jOx4+mgzbrezGL0jErnd9eX3ODt/NLH3NpX2XXt0WEYz9Q41HyMlV7eyUq/RHJRXWaksZYkEWHSitIJsjSOONFkBmEsLPD8VPS2fVYKfV1lXVoEVbERyy8HbbGDEbdm06DafOe3dB3+KSidSb95SyL8eUpdRetbySYyDSWsR4u8EF4Tr/SHUTl9ctOh6f0REvJzXjPRMM/uG+Pq5Fr+vGyA8YQj7n2LSvaw5zO2I07Nlf4MCFGY+CS0IE22AthnEptBKXbjFTFpLyTorkP5j8Tuvhru9BHZ3odJSOT2jFiZ5kxArbn5W+pg6Qiidm+JFmXZbtEVSsiS3HSJWXBxVJpBhWjMRpimKqdUMc272jyQ8KdEdpEVC0kEZtpE3Ul0ahdcIj492wnvhziGYHBR6s87fD4m9oPQ9r70iYQ3NcKbIo36uN7+Zd2w+C/jZr8XDIisg9NtI8="

before_install:
  - openssl aes-256-cbc -K $encrypted_ee3d73113e03_key -iv $encrypted_ee3d73113e03_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm install -g lerna

before_script:
  - git diff --exit-code

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(npm bin)/set-up-ssh --key "$encrypted_ee3d73113e03_key" --iv "$encrypted_ee3d73113e03_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    lerna run build &&
    lerna publish --yes --skip-git --repo-version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&

after_success:
  - npm run coveralls

notifications:
  slack:
    secure: ACnCq4lvEhY9YFErraIrKy6spRPy4z/+PdFg0Fd4I8WtFf+Bc5qkOr17m8+lb3in4SNGsPPk1eue6ZDHvBkGn190GQfWIqqqs6lXh5UgBB4e2boTKe5lMpTmme7FMNQuUgt69Xr2J2J8Mt2N0C8DWAm0yKPlPjN/2HUVzkHPnemOsYQDjJ0GJxLwYiL8NM1tgwFfOXloFMCQuQxHZvKPxdjBOS5PMkyOG/717j806bbED2yuT3PeZQEj8h3rPxSHJTmTOuP4CKZtnxv+4kf3YbHWNvRogpoizlUuUhwXO1xpNzH58T5sFgPIr353WJeBpvHeIe8F8ekuJYBJIbbRkA3eIrJemlJzOjMzuXtSEKAgolkbu0FWiZuJ/HTjeCJK4r56UzCzYDLMA316uXQ1Nlbk5hXhnkL08xWf5mtXWyXt2/4OUq1Tn8hpr9ZohulTj3B/lV3CV+rFzxeFyfTJi7JN3lmRkUIZRMv28Kh2aIn91UZqOHkhPY184HJOOPtU+JeJUXMZ1ltrnGDP1GBSJcXiLY8rK6mdcJrZPtonFB5MBrGNPKejuTuMFHqs9bY5Dtd3PVfRi4f7VThp0IUZt9qo3Us/9weboClQpRwkbsNogZHnu0w+bnOqLR/ZLVGx5P1XO1u3iO6zfinhFBatD1KsVNwTfJvv0NCy+gvyG6A=
