sudo: false
language: node_js
node_js:
  - "7.8"
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master  # (PRs to master, master merges, master pushes)

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: "UdU7dYh5Jef1yVYORQgpvRd3oVGi9UzPkoanUsAPF6Xmp/hpYN9bAG0nTnEE3OSFK4WehE2VdEQDtgvB/lgH6xgAmUcXv1ewNIZxRUvNQz7urYu6O+plbXlM+IUdDjOxGvj8P+ooWAiYuDYrChnfGOwcWydp1zOQc5RLmUSL9gi7E0hG119fCMPP+qJwaoDRpVQ2HdBQWLMCkcFqrRjYYEjf4ZYNhkNlL1jOx4+mgzbrezGL0jErnd9eX3ODt/NLH3NpX2XXt0WEYz9Q41HyMlV7eyUq/RHJRXWaksZYkEWHSitIJsjSOONFkBmEsLPD8VPS2fVYKfV1lXVoEVbERyy8HbbGDEbdm06DafOe3dB3+KSidSb95SyL8eUpdRetbySYyDSWsR4u8EF4Tr/SHUTl9ctOh6f0REvJzXjPRMM/uG+Pq5Fr+vGyA8YQj7n2LSvaw5zO2I07Nlf4MCFGY+CS0IE22AthnEptBKXbjFTFpLyTorkP5j8Tuvhru9BHZ3odJSOT2jFiZ5kxArbn5W+pg6Qiidm+JFmXZbtEVSsiS3HSJWXBxVJpBhWjMRpimKqdUMc272jyQ8KdEdpEVC0kEZtpE3Ul0ahdcIj492wnvhziGYHBR6s87fD4m9oPQ9r70iYQ3NcKbIo36uN7+Zd2w+C/jZr8XDIisg9NtI8="

before_install:
  - openssl aes-256-cbc -K $encrypted_ee3d73113e03_key -iv $encrypted_ee3d73113e03_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
  - git diff --exit-code

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(npm bin)/set-up-ssh --key "$encrypted_ee3d73113e03_key" --iv "$encrypted_ee3d73113e03_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

after_success:
  - npm run coveralls

notifications:
  # slack integration
  slack:
    # encrypted token for the meetuphq slack channel
    secure: "oW5B1Yow4dWFo8taSIcnR6PJX+V8SC1Af0Irec6JpfEDzKD4oFxY4UliROXKNiZzNHY4qqwtFGr9JSnHzQtnllhjD3RPwzlDYvwMXRrv2BYiQIX4Cod8P/SjjWPCX2j9qMijAVtViY+m5/OYK60/N5K+h0OS9KIhSl1NDJpDOsGDB+WZOVycHX3F6a3rSThgNaN8Ln34CqoFDmbidsYpuW3TP4QXbDbvT8bBnWyxWBgyOKEclUtyGGYCBuNjNEz7mfgEGAVqrLeyQANBu5BEoyP9n473LDHeM18IDbUh4yju1vAM5J/PPMiotoFcNR1ldEYKgoOcODONIQ7X6z9/1u7tA2AnJKkMZkFOJ3dLg+fGx8yTPO+jKUY0x0g7h1lsw0Re4GCyPuAlRTCYuWK1hvqIUEIhbPQF+XAFrhHcv1Ua5N7HHw2Nlu62q/j85GQHyKiWvu/FFM2TSEne+vA1DjliYLwhaNhiG6zVGKfEC2cM7yHtGxBhKrnKDw/wpBGn0d9hVVmmULJU2IZA/OmtvU/4o9nbSBWVHzGkmxgOL//6pRy67yORpsvtkffZFic2IN4GIcSuvgOLPvGtfSq44FW5wmEn6DuHihTHKfuIzZ3KjLgzwwFtNtVm2laxTds/PyG1zurIPN2mRVnms5ms/vbV9wErSm/Z0gAj74uB4sc="notifications:

